### ISSUE TITLE
bug: logger not set

### ISSUE THREAD

**Issue by SgtPooki** [libp2p/js-libp2p-amino-dht-bootstrapper#131]
Attempting to run this bootstrapper currently results in the following error:

```
root@ny5-js:~/code/js-libp2p-amino-dht-bootstrapper# node dist/src/index.js --config ~/bootstrapper-config.json
CodeError: logger not set
    at Object.get (file:///root/code/js-libp2p-amino-dht-bootstrapper/node_modules/libp2p/dist/src/components.js:66:27)
    at new PrometheusMetrics (file:///root/code/js-libp2p-amino-dht-bootstrapper/node_modules/@libp2p/prometheus-metrics/dist/src/index.js:170:31)
    at Object.metrics (file:///root/code/js-libp2p-amino-dht-bootstrapper/node_modules/@libp2p/prometheus-metrics/dist/src/index.js:321:16)
    at new Libp2pNode (file:///root/code/js-libp2p-amino-dht-bootstrapper/node_modules/libp2p/dist/src/libp2p.js:73:68)
    at createLibp2pNode (file:///root/code/js-libp2p-amino-dht-bootstrapper/node_modules/libp2p/dist/src/libp2p.js:339:12)
    at createLibp2p (file:///root/code/js-libp2p-amino-dht-bootstrapper/node_modules/libp2p/dist/src/index.js:44:24)
    at main (file:///root/code/js-libp2p-amino-dht-bootstrapper/dist/src/index.js:84:24) {
  code: 'ERR_SERVICE_MISSING',
  props: {}
}
```

**Comment by SgtPooki** [comment]
fixed by https://github.com/libp2p/js-libp2p-amino-dht-bootstrapper/commit/01611b91a2799925ac955ba42bade947c55728b1 & https://github.com/libp2p/js-libp2p-amino-dht-bootstrapper/commit/ffe222a0061044f0550a9463901f6c2125ed2368
